name: Push configurations

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
      - name: Push to S3
        run: |
          cd configurations \
          && for filename in ./*; do echo "on $filename" \
          && FILE=$(echo "$filename" | sed s#./##) \
          && aws s3 cp $FILE s3://serverboi-provision-configuration-bucket/$FILE ; done